
import javax.swing.DefaultListModel;
import java.util.Collection;
import java.util.List;
import java.util.ArrayList;
import java.util.Set;
import java.util.HashSet;
import java.util.Map;
import java.util.HashMap;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author u0_a562
 */
public class gui_D extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gui_D.class.getName());
    private DefaultListModel<String> listDLM;
    final private String[] toAdd = {
            "buku",
            "meja",
            "kursi",
            "tas",
            "pintu"
    };
    final private List<String> listData = new ArrayList<>();
    final private Set<String> setData = new HashSet<>();
    final private Map<String, String> mapData = new HashMap<>(); 
    

    /**
     * Creates new form gui
     */
    public gui_D() {
        initComponents();
        this.listDLM = new DefaultListModel<>();
        this.jListItem.setModel(listDLM);
        updateSizeLabel("list");
        updateSizeLabel("set");
        updateSizeLabel("map");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void addItem(String namaItem) {
        listDLM.addElement(namaItem);
    }
    
    private void updateSizeLabel(String type) {
        JLabel toChange;
        Collection size;
        toChange = switch (type) {
            case "list" -> jLabelListSize;
            case "set" -> jLabelSetSize;
            case "map" -> jLabelMapSize;
            default -> null;
        };
        size = switch (type) {
            case "list" -> listData;
            case "set" -> setData;
            case "map" -> null;
            default -> null;
        };
        
        if (toChange == null) {
            return; // invalid masukan
        }
        
        if (size == null) { // map
            toChange.setText("Size: %d -->".formatted(mapData.size()));
            return;
        }
        
        // ekslkusif koleksi
        toChange.setText("Size: %d -->".formatted(size.size()));
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListItem = new javax.swing.JList<>();
        jLabelNama = new javax.swing.JLabel();
        jTextFieldNamaItem = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonClearAll = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonAddList = new javax.swing.JButton();
        jButtonSaveList = new javax.swing.JButton();
        jLabelListSize = new javax.swing.JLabel();
        jButtonAddSet = new javax.swing.JButton();
        jLabelSetSize = new javax.swing.JLabel();
        jButtonSaveSet = new javax.swing.JButton();
        jButtonSaveMap = new javax.swing.JButton();
        jLabelMapSize = new javax.swing.JLabel();
        jButtonAddMap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Item GUI - Praktikum PBO D1");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jListItem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListItem);

        jLabelNama.setLabelFor(jTextFieldNamaItem);
        jLabelNama.setText("Nama Item:");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(this::jButtonAddActionPerformed);

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(this::jButtonDeleteActionPerformed);

        jButtonClearAll.setText("Clear All");
        jButtonClearAll.addActionListener(this::jButtonClearAllActionPerformed);

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(this::jButtonjButtonUpdateActionPerformed);

        jButtonAddList.setText("Insert List");
        jButtonAddList.addActionListener(this::jButtonAddListActionPerformed);

        jButtonSaveList.setText("Save List");
        jButtonSaveList.addActionListener(this::jButtonSaveListActionPerformed);

        jLabelListSize.setLabelFor(jButtonSaveList);
        jLabelListSize.setText("Size: 5 -->");

        jButtonAddSet.setText("Insert Set");
        jButtonAddSet.addActionListener(this::jButtonAddSetActionPerformed);

        jLabelSetSize.setLabelFor(jButtonSaveList);
        jLabelSetSize.setText("Size: 5 -->");

        jButtonSaveSet.setText("Save Set");
        jButtonSaveSet.addActionListener(this::jButtonSaveSetActionPerformed);

        jButtonSaveMap.setText("Save Map");
        jButtonSaveMap.addActionListener(this::jButtonSaveMapActionPerformed);

        jLabelMapSize.setLabelFor(jButtonSaveList);
        jLabelMapSize.setText("Size: 5 -->");

        jButtonAddMap.setText("Insert Map");
        jButtonAddMap.addActionListener(this::jButtonAddMapActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNamaItem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNama)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelListSize, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSetSize, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMapSize, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonAddList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaveList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaveSet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSaveMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAddMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveList)
                            .addComponent(jLabelListSize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddSet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveSet)
                            .addComponent(jLabelSetSize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAddMap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonSaveMap)
                            .addComponent(jLabelMapSize))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNamaItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        String text = jTextFieldNamaItem.getText();
        if (text.isEmpty()) {
            return;
        }
        addItem(text);
        jTextFieldNamaItem.setText("");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex();
        listDLM.removeElementAt(index);
        jTextFieldNamaItem.setText("");
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        // TODO add your handling code here:
        jTextFieldNamaItem.setText("");
        listDLM.removeAllElements();
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jButtonjButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjButtonUpdateActionPerformed
        // TODO add your handling code here:
        int index = jListItem.getSelectedIndex();
        String selected = jTextFieldNamaItem.getText();
        jTextFieldNamaItem.setText("");
        listDLM.setElementAt(selected, index);
    }//GEN-LAST:event_jButtonjButtonUpdateActionPerformed

    private void jButtonAddListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddListActionPerformed
        // TODO add your handling code here:
        for (String add : listData) {
            addItem(add);
        }
    }//GEN-LAST:event_jButtonAddListActionPerformed

    private void jButtonSaveListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveListActionPerformed
        // TODO add your handling code here:
        if (!listData.isEmpty()) { // ada isinya
            listData.clear(); // hapus
        }
        
        //timpa
        for (int i = 0; i < listDLM.getSize(); i++) {
            listData.add(listDLM.getElementAt(i));
        }
        
        // update count
        updateSizeLabel("list");
    }//GEN-LAST:event_jButtonSaveListActionPerformed

    private void jButtonAddSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSetActionPerformed
        // TODO add your handling code here:
        for (String add : setData) {
            addItem(add);
        }
    }//GEN-LAST:event_jButtonAddSetActionPerformed

    private void jButtonSaveSetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveSetActionPerformed
        // TODO add your handling code here:
        if (!setData.isEmpty()) { // ada isinya
            setData.clear(); // hapus
        }
        
        //timpa
        for (int i = 0; i < listDLM.getSize(); i++) {
            setData.add(listDLM.getElementAt(i));
        }
        
        // update count
        updateSizeLabel("set");
    }//GEN-LAST:event_jButtonSaveSetActionPerformed

    private void jButtonSaveMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveMapActionPerformed
        // TODO add your handling code here:
        if (!mapData.isEmpty()) {
            mapData.clear();
        }
        
        //timpa
        for (int i = 0; i < listDLM.getSize(); i++) {
            mapData.put(String.valueOf(i), listDLM.getElementAt(i));
        }
        
        // update count
        updateSizeLabel("map");
    }//GEN-LAST:event_jButtonSaveMapActionPerformed

    private void jButtonAddMapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMapActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < mapData.size(); i++) {
            addItem(mapData.get(String.valueOf(i)));
        }
    }//GEN-LAST:event_jButtonAddMapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gui_D().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddList;
    private javax.swing.JButton jButtonAddMap;
    private javax.swing.JButton jButtonAddSet;
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSaveList;
    private javax.swing.JButton jButtonSaveMap;
    private javax.swing.JButton jButtonSaveSet;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelListSize;
    private javax.swing.JLabel jLabelMapSize;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelSetSize;
    private javax.swing.JList<String> jListItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNamaItem;
    // End of variables declaration//GEN-END:variables
}
