package jdbc.ui;

import java.awt.Color;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import jdbc.model.Mahasiswa;
import jdbc.service.MysqlMahasiswaService;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author u0_a562
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());
    
    private static final MysqlMahasiswaService service = new MysqlMahasiswaService();
    DefaultListModel<String> listMhs;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        this.listMhs = new DefaultListModel<String>();
        this.jList1.setModel(listMhs);
        this.jStatusLabel.setText("");
        this.jList1.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String value = jList1.getSelectedValue();
                    if (value != null) {
                        String[] split = value.split(" \\(");
                        String NIM = split[1];
                        NIM = NIM.substring(0, NIM.length() - 1);
                        String Nama = split[0];
                        jTF_NIM.setText(NIM);
                        jTF_Nama.setText(Nama);
                    }
                }
            }
        });
        refreshList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private Color getStatusFG(String text) {
        return text.toLowerCase().contains("success") ? Color.GREEN : Color.RED;
    }
    
    private Color getStatusBG(String text) {
        return text.toLowerCase().contains("success") ? Color.decode("#010101") : Color.decode("#F2F2F2");
    }
    
    private void refreshList() {
        listMhs.clear();
        List<Mahasiswa> listData = service.getAll();
        for (Mahasiswa mhs : listData) {
            listMhs.addElement("%s (%d)".formatted(mhs.getNama(), mhs.getId()));
        }
        setStatus("Table successfully loaded!");
    }
    
    private void setStatus(String text) {
        jStatusLabel.setText(text);
        jStatusLabel.setForeground(getStatusFG(text));
    }
    
    private String addEscapeCharacters(String text) {
        String newText = text.replaceAll("'", "''");
        return newText;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jInsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jStatusLabel = new javax.swing.JLabel();
        jTF_NIM = new javax.swing.JTextField();
        jUpdButton = new javax.swing.JButton();
        jDelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTF_Nama = new javax.swing.JTextField();
        jRefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database Mahasiswa");
        setMinimumSize(new java.awt.Dimension(400, 300));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jInsButton.setText("Insert");
        jInsButton.addActionListener(this::jInsButtonActionPerformed);

        jLabel1.setLabelFor(jTF_NIM);
        jLabel1.setText("NIM");

        jStatusLabel.setBackground(new java.awt.Color(0, 0, 0));
        jStatusLabel.setFont(new java.awt.Font("Monocraft", 0, 12)); // NOI18N
        jStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jStatusLabel.setText("ERROR");
        jStatusLabel.setOpaque(true);

        jUpdButton.setText("Update");
        jUpdButton.addActionListener(this::jUpdButtonActionPerformed);

        jDelButton.setText("Delete");
        jDelButton.addActionListener(this::jDelButtonActionPerformed);

        jLabel2.setLabelFor(jTF_Nama);
        jLabel2.setText("Nama");

        jRefreshButton.setText("Refresh");
        jRefreshButton.addActionListener(this::jRefreshButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_NIM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTF_Nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jUpdButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jInsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jRefreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)
                        .addComponent(jDelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jRefreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTF_NIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jInsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTF_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jUpdButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDelButton)
                    .addComponent(jStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jInsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsButtonActionPerformed
        // TODO add your handling code here:
        Integer addNIM = Integer.valueOf(jTF_NIM.getText().isEmpty() ? "-999999" : jTF_NIM.getText());
        String addNama = jTF_Nama.getText();
        
        if (addNama.isEmpty()) {
            setStatus("Nama tidak boleh kosong!");
        } else {
            jTF_NIM.setText("");
            jTF_Nama.setText("");
            String res = addNIM == -999999 ? service.add(addNama) : service.add(new Mahasiswa(addNIM, addNama));
            setStatus(res);
            if ("Success!".equals(res)) {
                refreshList();
            }
        }
    }//GEN-LAST:event_jInsButtonActionPerformed

    private void jUpdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdButtonActionPerformed
        // TODO add your handling code here:
        Integer updNIM = Integer.valueOf(jTF_NIM.getText().isEmpty() ? "-999999" : jTF_NIM.getText());
        String updNama = addEscapeCharacters(jTF_Nama.getText());
        System.out.println(updNama);
        
        if (updNIM == -999999 || updNama.isEmpty()) {
            setStatus("Nama/NIM tidak boleh kosong!");
        } else {
            jTF_NIM.setText("");
            jTF_Nama.setText("");
            String res = service.update(new Mahasiswa(updNIM, updNama));
            setStatus(res);
            if ("Success!".equals(res)) {
                refreshList();
            }
        }
    }//GEN-LAST:event_jUpdButtonActionPerformed

    private void jDelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDelButtonActionPerformed
        // TODO add your handling code here:
        Integer deleteNIM = Integer.valueOf(jTF_NIM.getText().isEmpty() ? "-999999" : jTF_NIM.getText());
        
        if (deleteNIM == -999999) {
            setStatus("NIM tidak boleh kosong!");
        } else {
            jTF_NIM.setText("");
            jTF_Nama.setText("");
            String res = service.delete(new Mahasiswa(deleteNIM, ""));
            setStatus(res);
            if ("Success!".equals(res)) {
                refreshList();
            }
        }
        
    }//GEN-LAST:event_jDelButtonActionPerformed

    private void jRefreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRefreshButtonActionPerformed
        // TODO add your handling code here:
        refreshList();
    }//GEN-LAST:event_jRefreshButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jDelButton;
    private javax.swing.JButton jInsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JButton jRefreshButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jStatusLabel;
    private javax.swing.JTextField jTF_NIM;
    private javax.swing.JTextField jTF_Nama;
    private javax.swing.JButton jUpdButton;
    // End of variables declaration//GEN-END:variables
}
